Repository openfun/handbook, pull requests merged in 2021-01, with the labels that each got.

#6 ✨(slack) add our best practices when using Slack
  SUMMARY.md
  slack.md
Labels: improvement

#7 📝(git) add guideline for the commit message of a new release
  git.md
Labels: improvement, needs review

#8 🐛(git) fix guideline for the commit message of a new release
  git.md
Labels: bug, needs review
